env:
  node: true
  browser: true
  es2021: true

extends: airbnb-base

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  no-console: 0
  import/extensions: ['error', 'ignorePackages', { 'js': 'always' }]
  no-underscore-dangle: [2, { 'allow': ['_filename', '_dirname'] }]
